export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const ADD_IMAGE ='ADD_IMAGE';
export const SET_SPINNER ='SET_SPINNER';
export const SET_SPINNER_TO_FALSE ='SET_SPINNER_TO_FALSE';
export const GET_IMAGE ='GET_IMAGE';
